src/Entity/DetailProcess.php
<?php

namespace App\Entity;

use App\Repository\DetailProcessRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DetailProcessRepository::class)]
class DetailProcess
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private array $data = [];

    #[ORM\ManyToOne(inversedBy: 'detailProcesses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?HeaderProcess $header_process = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getData(): array
    {
        return $this->data;
    }

    public function setData(array $data): static
    {
        $this->data = $data;

        return $this;
    }

    public function getHeaderProcessId(): ?HeaderProcess
    {
        return $this->header_process;
    }

    public function setHeaderProcessId(?HeaderProcess $header_process): static
    {
        $this->header_process = $header_process;

        return $this;
    }
}

src/Entity/HeaderProcess.php
<?php

namespace App\Entity;

use App\Repository\HeaderProcessRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HeaderProcessRepository::class)]
class HeaderProcess
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $file_name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $execution_date = null;

    /**
     * @var Collection<int, DetailProcess>
     */
    #[ORM\OneToMany(targetEntity: DetailProcess::class, mappedBy: 'header_process_id', cascade: ['persist', 'remove'])]
    private Collection $detailProcesses;

    public function __construct()
    {
        $this->detailProcesses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(string $file_name): static
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getExecutionDate(): ?\DateTimeInterface
    {
        return $this->execution_date;
    }

    public function setExecutionDate(\DateTimeInterface $execution_date): static
    {
        $this->execution_date = $execution_date;

        return $this;
    }

    /**
     * @return Collection<int, DetailProcess>
     */
    public function getDetailProcesses(): Collection
    {
        return $this->detailProcesses;
    }

    public function addDetailProcess(DetailProcess $detailProcess): static
    {
        if (!$this->detailProcesses->contains($detailProcess)) {
            $this->detailProcesses->add($detailProcess);
            $detailProcess->setHeaderProcessId($this);
        }

        return $this;
    }

    public function removeDetailProcess(DetailProcess $detailProcess): static
    {
        if ($this->detailProcesses->removeElement($detailProcess)) {
            // set the owning side to null (unless already changed)
            if ($detailProcess->getHeaderProcessId() === $this) {
                $detailProcess->setHeaderProcessId(null);
            }
        }

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Serializer\SerializerInterface;
use App\Entity\HeaderProcess;
use App\Entity\DetailProcess;


class DashboardController extends AbstractController
{
    private EntityManagerInterface $entityManager;


    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/dashboard', name: 'app_dashboard')]
    public function index(): Response
    {
        return $this->render('dashboard/index.html.twig', [
            'groups' => $this->entityManager->getRepository(HeaderProcess::class)->findAll()
        ]);
    }

    #[Route('/get-group-data', name: 'app_get_group_data')]
    public function getGroupData(Request $request, SerializerInterface $serializer): JsonResponse
    {
        $groupId = $request->get('groupId');
        $headerProcess = $this->entityManager->getRepository(HeaderProcess::class)->find($groupId);
        $data = $this->entityManager->getRepository(DetailProcess::class)->findOneBy(['header_process' => $headerProcess]);
        $data = $data->getData();

        foreach($data['osTotal'] as $key => $os) {
            $osFormattedData[] = [
                'name' => $key,
                'y' => $os
            ];
        }

        return new JsonResponse([
            'data' => $data,
            'osFormattedData' => $osFormattedData
            ]
        );
    }
}

src/Controller/RootController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class RootController extends AbstractController
{
    #[Route('/', name: 'app_root')]
    public function index(): Response
    {
        return $this->render('root/index.html.twig', [
            'controller_name' => 'RootController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.3/font/bootstrap-icons.min.css">
        {% block stylesheets %}
        
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard{% endblock %}

{% block stylesheets %}
        <style>
            pre {
                background-color: #f7f7f7;
                border: 1px solid #ddd;
                padding: 10px;
                border-radius: 4px;
                overflow-x: auto;
                white-space: pre-wrap; 
                max-height: 24em;
            }
                #chart-container {
                width: 100%;
                height: 400px; /* Adjust height as needed */
            }
        </style>
{% endblock %}

{% block body %}
<div class="container mt-5">
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Dashboard</h5>
                <div class="row">
                    <div class="col-4">
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Select a group of data</label>
                            <select name="group" id="group" class="form-select">
                                <option value="">Select a group</option>
                                {% for group in groups %}
                                    <option value="{{group.id}}">{{group.id}} - {{group.executionDate | date}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="col-2">
                        <button class="btn btn-primary mt-3" id="seach">Search</button>
                    </div>
                </div>

                <div class="row mt-4">
                    <div class="spinner-border text-primary" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                    <div class="col-6">
                        <pre id="json-data" class="content"></pre>
                    </div>
                    <div class="col-6">
                        <div class="container mt-2">
                            <div id="chart-container" class="content"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% block javascripts %}
<script src="https://code.highcharts.com/highcharts.js"></script>
<script>
    (function() {
        $('.content').hide();
        $('.spinner-border').hide();

        const route = "{{ path('app_get_group_data')}}";

        $('#seach').click(() => {
            const group = $('#group').val();

            if(group === '' || group === undefined) {
                alert('Please select a group');
                return;
            }

            $.ajax({
                url: route,
                method: 'POST',
                data: {groupId: group},
                beforeSend: function( xhr ) {
                    $('.content').hide();
                    $('.spinner-border').show();
                }
            }).done(function(data){
                $('#json-data').html(JSON.stringify(data.data, null, 2));
                initializePieChart(data.osFormattedData);
                $('.content').show();
                $('.spinner-border').hide();
            });
        });



    })();

    function initializePieChart(chartData){
        Highcharts.chart('chart-container', {
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Operating System'
            },
            series: [{
                name: 'Usage',
                data: chartData,
                innerSize: '50%', // Optional: For a donut chart
            }],
            plotOptions: {
                pie: {
                    dataLabels: {
                        enabled: true,
                        format: '{point.name}: {point.y}'
                    }
                }
            }
        });
    }
</script>
{% endblock %}

{% endblock %}

templates/root/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Login{% endblock %}

{% block body %}
<div class="container mt-5">
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Login</h5>
                <p class="card-text">Please login to continue.</p>
                <a href="{{ path('hwi_oauth_service_redirect', {'service': 'google' }) }}">
                    <i class="bi bi-google"></i> Login with Google
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}